"""New Migration

Revision ID: 8eaa62cdc105
Revises: 11f522d7d803
Create Date: 2023-06-04 01:18:36.048443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eaa62cdc105'
down_revision = '11f522d7d803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
