"""New Migration

Revision ID: 98673309f849
Revises: 6000f27909b9
Create Date: 2023-06-05 20:32:20.714391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98673309f849'
down_revision = '6000f27909b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
